-- Endereco e hemocentro sao dados de catalogo: sao lidos por todos e nunca
-- alterados por doador. O endereco fica normalizado porque a copia embutida que
-- o app gravava no agendamento e na bolsa nao tinha integridade referencial.

CREATE TABLE endereco (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro  VARCHAR(200) NOT NULL,
    numero      VARCHAR(20)  NOT NULL,
    complemento VARCHAR(120),
    bairro      VARCHAR(120) NOT NULL,
    cidade      VARCHAR(120) NOT NULL,
    estado      VARCHAR(2)   NOT NULL,
    cep         VARCHAR(9)   NOT NULL
);

CREATE TABLE hemocentro (
    id                      VARCHAR(20)  PRIMARY KEY,
    nome                    VARCHAR(200) NOT NULL,
    telefone                VARCHAR(30)  NOT NULL,
    email                   VARCHAR(200) NOT NULL,
    horario_abertura        TIME         NOT NULL,
    horario_fechamento      TIME         NOT NULL,
    -- Nome com digito no meio: o naming strategy do Hibernate nao produz
    -- "funcionamento_24_horas" de forma confiavel, e como o ddl-auto e
    -- validate a coluna precisa bater exatamente com o @Column da entidade.
    funcionamento_24_horas  BOOLEAN      NOT NULL DEFAULT FALSE,
    capacidade_coleta       DOUBLE PRECISION NOT NULL DEFAULT 0,
    endereco_id             BIGINT       NOT NULL REFERENCES endereco (id)
);

CREATE INDEX idx_hemocentro_endereco ON hemocentro (endereco_id);