-- User e Doador viram uma unica tabela: a heranca do app nao mapeia para o
-- Postgres sem discriminated column, e nada no dominio precisa do tipo
-- separado. "senha" guarda o hash BCrypt, nunca a senha digitada.

CREATE TABLE doador (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(200) NOT NULL,
    email          VARCHAR(200) NOT NULL,
    senha          VARCHAR(100) NOT NULL,
    -- Chave logica do dominio e o CPF: e por ele que o app liga doador e
    -- agendamento, e por isso ele e imutavel apos o cadastro. Guardamos so os
    -- 11 digitos, normalizados, para que o UNIQUE abaixo valha de verdade.
    cpf            VARCHAR(11)  NOT NULL,
    tipo_sanguineo VARCHAR(2)   NOT NULL CHECK (tipo_sanguineo IN ('A', 'B', 'AB', 'O')),
    fator_rh       VARCHAR(8)   NOT NULL CHECK (fator_rh IN ('POSITIVO', 'NEGATIVO')),
    CONSTRAINT uk_doador_email UNIQUE (email),
    CONSTRAINT uk_doador_cpf   UNIQUE (cpf)
);

CREATE INDEX idx_doador_email_lower ON doador (lower(email));