-- agendamento aponta para doador e hemocentro por chave estrangeira. No app a
-- ligacao era por uma copia do objeto Hemocentro e por cpfDoador em texto, o
-- que permitia agendamento orfao se o cadastro mudasse.

CREATE TABLE agendamento (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id         BIGINT       NOT NULL REFERENCES doador (id),
    hemocentro_id     VARCHAR(20)  NOT NULL REFERENCES hemocentro (id),
    data              DATE         NOT NULL,
    hora              TIME         NOT NULL,
    status            VARCHAR(10)  NOT NULL CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'REALIZADO')),
    data_confirmacao  DATE,
    observacoes       VARCHAR(500)
);

-- A listagem de agendamentos do doador e sempre ordenada por data e hora, e a
-- consulta de elegibilidade filtra exatamente pelas mesmas colunas.
CREATE INDEX idx_agendamento_doador ON agendamento (doador_id, data, hora);