-- Um lote de bolsas por agendamento. No app essa regra era apenas uma varredura
-- linear em PrefsManager.getBolsaPorAgendamento, que duas requisicoes simultaneas
-- poderiam furar; o UNIQUE abaixo transforma a regra em garantia do banco.
--
-- tipo_sanguineo e fator_rh sao os do doador no momento da coleta, nao os do
-- agendamento: a bolsa herda data e hemocentro do agendamento, mas o sangue vem
-- de quem doou.

CREATE TABLE bolsa_sangue (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo             VARCHAR(20)  NOT NULL,
    tipo_sanguineo     VARCHAR(2)   NOT NULL CHECK (tipo_sanguineo IN ('A', 'B', 'AB', 'O')),
    fator_rh           VARCHAR(8)   NOT NULL CHECK (fator_rh IN ('POSITIVO', 'NEGATIVO')),
    data_coleta        DATE         NOT NULL,
    -- Regra de validade: sempre 42 dias apos a coleta.
    data_validade      DATE         NOT NULL,
    volume_ml          INTEGER      NOT NULL CHECK (volume_ml BETWEEN 200 AND 470),
    quantidade         INTEGER      NOT NULL CHECK (quantidade BETWEEN 1 AND 6),
    status             VARCHAR(12)  NOT NULL CHECK (status IN ('DISPONIVEL', 'RESERVADA', 'UTILIZADA', 'VENCIDA')),
    hemocentro_origem_id VARCHAR(20) NOT NULL REFERENCES hemocentro (id),
    agendamento_id     BIGINT       NOT NULL REFERENCES agendamento (id),
    receptor_cpf       VARCHAR(11),
    data_destinacao    DATE,
    CONSTRAINT uk_bolsa_codigo       UNIQUE (codigo),
    CONSTRAINT uk_bolsa_agendamento  UNIQUE (agendamento_id)
);

CREATE INDEX idx_bolsa_doador ON bolsa_sangue (agendamento_id);