-- Saldo de bolsas por hemocentro e tipo sanguineo. Um registro por combinacao:
-- o UNIQUE garante que a coleta sempre incremente a mesma linha em vez de criar
-- entradas soltas que teriam que ser somadas na leitura.
CREATE TABLE estoque_sangue (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hemocentro_id         VARCHAR(20) NOT NULL REFERENCES hemocentro (id),
    tipo_sanguineo        VARCHAR(2)  NOT NULL CHECK (tipo_sanguineo IN ('A', 'B', 'AB', 'O')),
    fator_rh              VARCHAR(8)  NOT NULL CHECK (fator_rh IN ('POSITIVO', 'NEGATIVO')),
    quantidade_disponivel INTEGER     NOT NULL DEFAULT 0 CHECK (quantidade_disponivel >= 0),
    quantidade_minima     INTEGER     NOT NULL DEFAULT 0 CHECK (quantidade_minima >= 0),
    CONSTRAINT uk_estoque UNIQUE (hemocentro_id, tipo_sanguineo, fator_rh)
);
CREATE INDEX idx_estoque_hemocentro ON estoque_sangue (hemocentro_id);
