-- Triagem clinica por visita. O peso, a pressao e a hemoglobina nao pertencem ao
-- doador (mudam a cada visita), e sim ao evento de doacao, por isso ficam aqui.
CREATE TABLE triagem_doador (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id        BIGINT           NOT NULL REFERENCES doador (id),
    data             DATE             NOT NULL,
    peso_kg          DOUBLE PRECISION NOT NULL CHECK (peso_kg > 0),
    pressao_arterial VARCHAR(20)      NOT NULL,
    hemoglobina      DOUBLE PRECISION NOT NULL CHECK (hemoglobina > 0),
    -- Calculado da regra de aptidao no momento do registro, e guardado para que
    -- um ajuste futuro na regra nao reescreva o passado.
    apto             BOOLEAN          NOT NULL,
    observacoes      VARCHAR(500)
);
CREATE INDEX idx_triagem_doador ON triagem_doador (doador_id, data);
