-- Avisos ao doador. lida e um estado, nao um delete: o historico de avisos e
-- mantido para que o doador possa revisar o que recebeu.
CREATE TABLE notificacao (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id  BIGINT       NOT NULL REFERENCES doador (id),
    titulo     VARCHAR(120) NOT NULL,
    mensagem   VARCHAR(500) NOT NULL,
    criada_em  TIMESTAMP    NOT NULL,
    lida       BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_notificacao_doador ON notificacao (doador_id, criada_em);
